version: "2"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: dbname
    env_file:
      - .env
  app:
    build: .
    links:
      - mysql
    ports:
      - "8899:8080"
    volumes:
      - ./clients/temp:/usr/src/app/clients/temp
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 1234
      MYSQL_HOST: mysql
      DB_HOST: mysql
    depends_on:
      - mysql
    env_file:
      - .env
